<?php

namespace refaltor\CustomItems\Items;

use pocketmine\item\Item;

class Items extends Item
{
    /** @var int */
    public $durability = 100;

    /** @var int */
    public $defense = 0;

    public function __construct(int $defense, int $durability, int $id, int $meta = 0, string $name = "Unknown")
    {
        $this->durability = $durability;
        $this->defense = $defense;
        parent::__construct($id, $meta, $name);
    }

    public function getMaxDurability(): int
    {
        return $this->durability;
    }

    public function getDefensePoints(): int
    {
        return $this->defense;
    }

    public function applyDamage(int $amount): bool
    {
        $this->setLore(['Durability : ' . (self::getMaxDurability() - $amount)]);
        $durability = explode(' : ', implode(' ', $this->getLore()));
        if (intval($durability[1]) < 0) {
            $this->setCount(0);
        }
        return parent::applyDamage($amount); // TODO: Change the autogenerated stub
    }
}